<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVoapGZA\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVoapGZA/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVoapGZA.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVoapGZA\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVoapGZA\appAppKernelProdContainer([
    'container.build_hash' => 'VoapGZA',
    'container.build_id' => 'efab7e31',
    'container.build_time' => 1778001487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVoapGZA');
